/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_itpglb_Main */

#ifndef _Included_com_example_itpglb_Main
#define _Included_com_example_itpglb_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_itpglb_Main
 * Method:    Connect_to_bluetooth_device
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_itpglb_Main_Connect_1to_1bluetooth_1device
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
